### ISSUE TITLE
Use mip_sdk on Arduino Zero

### ISSUE THREAD

**Issue by Alex-Beh** [LORD-MicroStrain/mip_sdk#66]
Hi all, I would like to use mip_sdk on Arduino Zero to read data from microstrain imu. I have tried to compress the [ArduinoLibrary](https://github.com/LORD-MicroStrain/mip_sdk/tree/feature/Arduino/ArduinoLibrary) and add into arduino ide but still facing some compilation error. May I know is the branch ready to be used?

--- update ---
managed to compile the program code. But still want to know is it stable to be used? I assumed yes.

**Comment by dacuster** [comment]
Hi Alex,

It was difficult to figure out how to configure CMake for Arduino and it turns out that most projects created for this purpose were discontinued. Due to that lack of support, we stopped developing this branch for now.

From what I can remember, the CMake configuration I used had limitations on the supported boards/processors and I don't remember if Zero was supported. If you did get it working that's great to hear, but this branch isn't quite stable and we unfortunately won't be continuing development for the foreseeable future.

I will add a note in the readme of the state of this branch for future reference. Sorry for the confusion. If you have any further issues feel free to reach out and we will do our best to support it.

**Comment by Alex-Beh** [comment]
@dacuster Hi, I tried to follow the hardware setup here and connect the RS232 TX & RX into a RS232-TTL max3232 converter then connect into my arduino board. I have successfully compiled and uploaded the code to arduino board but the code stuck at [mip_base_ping](https://github.com/LORD-MicroStrain/mip_sdk/blob/2f8bae6f0ef3b73976438e13d9dba9f4d32ef9d2/examples/AVR/AVR.ino#L145). There is no response from the function.

Any hint? Do you all communicate with Microstrain IMU using arduino board successfully before?

**Comment by dacuster** [comment]
@Alex-Beh The furthest we got with Arduino support was compilation. When we started testing, the communication was very spotty and we ended up discontinuing support on the Arduino branch. The MIP SDK has also had quite a few updates since then. I was able to get the idle command sent to the device, but the response was coming back in bits and pieces. I'd say the first step, if you do want to continue with this, is to create a processing system for the response packets to allow for the full packet to be received before processing it.
